### ISSUE TITLE
Error triggered by an Enum.* pipeline

### ISSUE THREAD

**Issue by mat-hek** [hissssst/tria#4]
Hi, thanks for the lib! I get the following error:
```
failed_to_compile: defmodule TriaGlobalContext do
                     def generate_generate(accepted_formats_nil_520) do
                       case_statement_clauses_nil_552 =
                         Enum.concat(
                           Enum.flat_map(
                             accepted_formats_nil_520,
                             fn x_nil_968 ->
                               {:__aliases__, _meta_nil_1032, _module_nil_1064} = HERE_HITS!(ast_nil_1096)

                               [
                                 {:->, [],
                                  [
                                    [
                                      case x_nil_968 do
                                        {:__aliases__, _meta_nil_1384, _module_nil_1416} = ast_nil_1448 ->
                                          {:%, [], [x_nil_968, {:%{}, [], []}]}

                                        ast_nil_1480 when :erlang.is_atom(ast_nil_1480) ->
                                          {:%, [], [x_nil_968, {:%{}, [], []}]}

                                        ast_nil_1512 ->
                                          x_nil_968
                                      end
                                    ],
                                    true
                                  ]}
                               ]
                             end
                           ),
                           [{:->, [generated: true], [[{:_else, [generated: true], Generate}], false]}]
                         )
                     end
                   end

19:37:18.565 [error] GenServer TriaGlobalContext terminating
** (CompileError) Elixir.TriaGlobalContext.ex:2728: undefined function ast/0 (expected TriaGlobalContext to define such a function or for it to be imported, but none are available)
    (elixir 1.13.4) src/elixir_locals.erl:115: anonymous fn/4 in :elixir_locals.ensure_no_undefined_local/3
    (elixir 1.13.4) src/elixir_module.erl:121: anonymous fn/8 in :elixir_module.compile/5
    (elixir 1.13.4) src/elixir_erl_compiler.erl:12: anonymous fn/2 in :elixir_erl_compiler.spawn/1
Last message (from #PID<0.94.0>): :generate
State: %{definitions: %{{Generate, :generate, 1} => {:def, [{[{:accepted_formats, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 2], 200}], [], [do: {:=, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 3], [{:case_statement_clauses, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 3], 232}, {{:., [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 15], [Enum, :concat]}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 15], [{{:., [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 10], [Enum, :flat_map]}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 10], [{{:., [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 5], [Enum, :map]}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 5], [{:accepted_formats, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 4], 200}, {:fn, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 5], [{:->, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 6], [[{:=, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 6], [{:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 6], [:__aliases__, {:_meta, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 6], 264}, {:_module, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 6], 296}]}, {:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 6], 328}]}], {:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 0], [:%, [], [{:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 6], 328}, {:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 0], [:%{}, [], []]}]]}]}, {:->, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 7], [[{:when, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex"], [{:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 7], 360}, {{:., [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 7], [:erlang, :is_atom]}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 7], [{:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 7], 360}]}]}], {:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 0], [:%, [], [{:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 7], 360}, {:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 0], [:%{}, [], ...]}]]}]}, {:->, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 8], [[{:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 8], 392}], {:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 8], 392}]}]}]}, {:fn, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 10], [{:->, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 10], [[{:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 10], 424}], [{:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 0], [:->, [], [[{:ast, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 12], 424}], true]]}]]}]}]}, [{:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 0], [:->, [generated: true], [[{:{}, [file: "/Users/matheksm/Desktop/sm/membrane_test/try_tria/lib/try_tria.ex", line: 0], [:_else, [generated: true], Generate]}], false]]}]]}]}]}]}}, name: TriaGlobalContext}
Client #PID<0.94.0> is alive

    (stdlib 4.0.1) gen.erl:237: :gen.do_call/4
    (elixir 1.13.4) lib/gen_server.ex:1027: GenServer.call/3
    (tria 0.0.1) lib/tria/compiler.ex:90: Tria.Compiler.compile/2
    (tria 0.0.1) lib/mix/tasks/compile.tria.ex:42: Mix.Tasks.Compile.Tria.compile/2
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
```

when trying to compile this:

```elixir
defmodule Generate do
  def generate(accepted_formats) do
    case_statement_clauses =
      accepted_formats
      |> Enum.map(fn
        {:__aliases__, _meta, _module} = ast -> quote do: %unquote(ast){}
        ast when is_atom(ast) -> quote do: %unquote(ast){}
        ast -> ast
      end)
      |> Enum.flat_map(fn ast ->
        quote do
          unquote(ast) -> true
        end
      end)
      |> Enum.concat(
        quote generated: true do
          _else -> false
        end
      )
  end
end
```

**Comment by hissssst** [comment]
Good catch, thanks!
